### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by relf** [relf/egobox#90]
Some ideas for further developments:
- [ ] Make infill criterion a trait to allow to use `EgorSolver` with custom criterion
- [ ] Implement multi-fidelity gaussian process
- [ ] Expand optimizer constraints handling (not only <0)
- [ ] Make some benchmarks (egobox vs SMT)
- [ ] ...
